### ISSUE TITLE
Android 7.1

### ISSUE THREAD

**Issue by Voha888** [j-hc/revanced-magisk-module#183]
I search magisk module for android 7.1. Where download version 17.33.42 ?

**Comment by j-hc** [comment]
you need to find the latest revanced patches version that supports android 7 and lock it in the config.toml using `patches-version`

**Comment by Voha888** [comment]
@j-hc but in the releases section of the magisk module, I didn't find that version.  Please send this version.  I will save it on different sites for future reference.  Thank you

**Comment by MatadorProBr** [comment]
After searching around I finded where is the latest patches version that supports v17.33.42
It's [v2.100.3](https://github.com/revanced/revanced-patches/releases/tag/v2.100.3)

After [v2.101.0](https://github.com/revanced/revanced-patches/releases/tag/v2.101.0) the support for v17.33.42 is removed forever as stated here: https://github.com/revanced/revanced-patches/commit/1b6a64b49c54ab53df463981a9ad7ec67729939f

**Comment by Voha888** [comment]
Thank you! I understand you. But do you have the opportunity to send me the original youtube-revanced-magisk-v17.33.42-all.zip file?

**Comment by MatadorProBr** [comment]
Just fork the repo, go to `config.toml`, change `patches-version` to `v2.100.3` & `version` to `17.33.42` and then just build using the actions page

**Comment by Voha888** [comment]
I changed the file https://github.com/Voha888/revanced-magisk-module/blob/main/config.toml
Build app https://github.com/Voha888/revanced-magisk-module/releases . But its crashed

**Comment by MatadorProBr** [comment]
Oh yeah you have to downgrade the integrations version too

**Comment by Voha888** [comment]
ThankYou! Its helps me - Youtube app is works, video is playing good! 
Icon Youtube app changed to RevancedIcon.
**But Revanced features not works, and when I go to Settings>Revanced app is crashed**

**Comment by MatadorProBr** [comment]
Now it seems to be the CLI but here is the catch, you can't change the version of the CLI in the config.toml file (a suggestion for you @j-hc)

But you can change the link on [this line](https://github.com/Voha888/revanced-magisk-module/blob/main/utils.sh#L45) to this: https://api.github.com/repos/revanced/revanced-cli/releases/tags/v2.16.0

and I recommend removing all the --rip-lib arguments from https://github.com/Voha888/revanced-magisk-module/blob/main/utils.sh#L240 and https://github.com/Voha888/revanced-magisk-module/blob/main/utils.sh#L392 since now we are using the official ReVanced CLI instead of the j-hc fork, it's good to make this so the official ReVanced CLI doesn't stop the build/question itself what is that argument

**Comment by Voha888** [comment]
Please, check my file https://github.com/Voha888/revanced-magisk-module/blob/main/utils.sh
I changed only lines which You mentioned
After changes, its build apk, not a magisk module
