### ISSUE TITLE
It's just causing bootloop everytime i try to install it

### ISSUE THREAD

**Issue by tr1p0p** [j-hc/revanced-magisk-module#257]
It seem Youtbe Music and Youtube magisk modules just cause bootloop. So hum, what can we do in this case ?

Also, how a modules that just patches and app can cause a bootloop ? 

(CherishOS Android 13).

EDIT : So it really BREAK MY SYSTEM Magisk core didn't boot, remove modules didn't boot. Bootloop again and again. It's REALLY infuating that a magisk module JUST for youtube cause bootloop...

I think root way is like more UNSTABLE that non-root way ? That's really weird.

So be warned. On android 13, this modules just cause bootloop and cannot be repaired. For no reasons.

**Comment by j-hc** [comment]
probably a rom issue and quite likely has nothing to do with the module. you are the only person having this issue on A13 or otherwise.

does it go into a bootloop right after flashing or after a reboot. try without rebooting and see if it works.

also if you have other modules like dolby that intervenes with mountpoints, that could also be the reason.

**Comment by tr1p0p** [comment]
I have only safetynetfix. And now ROM dev tell me it's my modules. So really i don't know how to debug that. Will try to get the logs

**Comment by tr1p0p** [comment]
Yeah it seem changing the rom (Go to evolutionX) fix the problem here
